services:
  postgres:
    image: postgres:15
    container_name: FiapCloudGames.Jogos-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: FiapCloudGames.Jogos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./src/FiapCloudGames.Jogos.API/Dockerfile
    image: fcg-app
    container_name: FiapCloudGames.Jogos-api
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=FiapCloudGames.Jogos;Username=admin;Password=admin123
      - ASPNETCORE_URLS=http://+:5001

volumes:
  postgres_data:
